<?php
/**
 * @file
 * Main hooks for Islandora Usage Reports.
 */

/**
 * Implements hook_menu().
 */
 function islandora_usage_reports_menu() {
  return array(
    'admin/islandora/tools/usage_reports' => array(
      'title' => 'Islandora Usage Stats Reports',
      'description' => 'Configure Usage Stats Reports.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_usage_reports_admin_form'),
      'access arguments' => array('administer site configuration'),
      'type' => MENU_NORMAL_ITEM,
      'file' => 'includes/admin.form.inc',
    ),
  );
} 

/**
 * Implements hook_block_info(). Creates blocks.
 * DRUPAL_CACHE_PER_PAGE set so that not too many API calls are made.
 */

function islandora_usage_reports_block_info() {
  return array(
    'usage_reports_thisobject' => array(
      'visibility' => BLOCK_VISIBILITY_LISTED,
      'pages' => 'islandora/object/*',
      'info' => t('Object usage'),
    ),
  );
}

/**
 * Implements hook_block_view().
 */

function islandora_usage_reports_block_view($delta) {
  $to_render = array();

  $object = menu_get_object('islandora_object', 2);
  global $base_url;

// Calls on the islandora_usage_stats_callbacks module 'API' to grab stats.
  $usage_stats_json = file_get_contents("{$base_url}/islandora_usage_stats_callbacks/object_stats/{$object->id}");

// Turns the JSON output into a usable array.
  $usage_stats_array = json_decode($usage_stats_json, TRUE);

// Counts the number of views and number of downloads. Would be nice to get rid of legacy views..
  $views = count($usage_stats_array['views']) + $usage_stats_array['legacy-views'];
  $downloads = count($usage_stats_array['downloads']) + $usage_stats_array['legacy-downloads'];

  $to_render['content'] = '<div id="object_views">Views: ' . $views . '</div><div id="object_downloads">Downloads: ' . $downloads . '</div>';

  return $to_render;
}

